// Package problem provides RFC 9457 Problem Details for HTTP APIs helper.
//
// This package is optional and REST-oriented. It is not used automatically
// and should not be applied to GraphQL or OAuth responses.
package problem

import (
	"encoding/json"
	"net/http"

	cf_http "github.com/caerus-framework/caerus-framework-http"
)

// Problem represents an RFC 9457 Problem Details response.
type Problem struct {
	// Type is a URI reference that identifies the problem type.
	// When this member is not present, its value is assumed to be "about:blank".
	Type string `json:"type,omitempty"`

	// Title is a short, human-readable summary of the problem type.
	// It SHOULD NOT change from occurrence to occurrence of the problem,
	// except for purposes of localization.
	Title string `json:"title,omitempty"`

	// Status is the HTTP status code generated by the origin server for this
	// occurrence of the problem.
	Status int `json:"status,omitempty"`

	// Detail is a human-readable explanation specific to this occurrence of
	// the problem.
	Detail string `json:"detail,omitempty"`

	// Instance is a URI reference that identifies the specific occurrence of
	// the problem.
	Instance string `json:"instance,omitempty"`

	// RequestID is an extension field for request correlation.
	RequestID string `json:"request_id,omitempty"`

	// Extensions allows additional fields to be added to the response.
	Extensions map[string]any `json:"-"`
}

// MarshalJSON implements json.Marshaler to support extensions.
func (p Problem) MarshalJSON() ([]byte, error) {
	type Alias Problem
	if len(p.Extensions) == 0 {
		return json.Marshal(Alias(p))
	}

	// Merge extensions into the response
	m := make(map[string]any)
	b, err := json.Marshal(Alias(p))
	if err != nil {
		return nil, err
	}
	if err := json.Unmarshal(b, &m); err != nil {
		return nil, err
	}
	for k, v := range p.Extensions {
		m[k] = v
	}
	return json.Marshal(m)
}

// Write writes a Problem Details response to the HTTP response writer.
// The request's correlation ID (RequestIDFrom) is used for request_id when
// the problem does not already carry one. It returns an error if JSON
// encoding fails.
func Write(w http.ResponseWriter, r *http.Request, p Problem) error {
	if p.Status == 0 {
		p.Status = http.StatusInternalServerError
	}
	if p.Type == "" {
		p.Type = "about:blank"
	}
	if p.RequestID == "" {
		p.RequestID = cf_http.RequestIDFrom(r)
	}

	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(p.Status)
	return json.NewEncoder(w).Encode(p)
}

// New creates a new Problem Details response with the given status and title.
func New(status int, title string) Problem {
	return Problem{
		Status: status,
		Title:  title,
	}
}

// WithType sets the problem type URI.
func (p Problem) WithType(typ string) Problem {
	p.Type = typ
	return p
}

// WithDetail sets the problem detail.
func (p Problem) WithDetail(detail string) Problem {
	p.Detail = detail
	return p
}

// WithInstance sets the problem instance URI.
func (p Problem) WithInstance(instance string) Problem {
	p.Instance = instance
	return p
}

// WithRequestID sets the request ID for correlation.
func (p Problem) WithRequestID(requestID string) Problem {
	p.RequestID = requestID
	return p
}

// WithExtension adds an extension field to the response.
func (p Problem) WithExtension(key string, value any) Problem {
	if p.Extensions == nil {
		p.Extensions = make(map[string]any)
	}
	p.Extensions[key] = value
	return p
}

// BadRequest creates a 400 Bad Request problem.
func BadRequest(title, detail string) Problem {
	return New(http.StatusBadRequest, title).WithDetail(detail)
}

// Unauthorized creates a 401 Unauthorized problem.
func Unauthorized(title, detail string) Problem {
	return New(http.StatusUnauthorized, title).WithDetail(detail)
}

// Forbidden creates a 403 Forbidden problem.
func Forbidden(title, detail string) Problem {
	return New(http.StatusForbidden, title).WithDetail(detail)
}

// NotFound creates a 404 Not Found problem.
func NotFound(title, detail string) Problem {
	return New(http.StatusNotFound, title).WithDetail(detail)
}

// MethodNotAllowed creates a 405 Method Not Allowed problem.
func MethodNotAllowed(title, detail string) Problem {
	return New(http.StatusMethodNotAllowed, title).WithDetail(detail)
}

// Conflict creates a 409 Conflict problem.
func Conflict(title, detail string) Problem {
	return New(http.StatusConflict, title).WithDetail(detail)
}

// TooManyRequests creates a 429 Too Many Requests problem.
func TooManyRequests(title, detail string) Problem {
	return New(http.StatusTooManyRequests, title).WithDetail(detail)
}

// InternalServerError creates a 500 Internal Server Error problem.
func InternalServerError(title, detail string) Problem {
	return New(http.StatusInternalServerError, title).WithDetail(detail)
}

// ServiceUnavailable creates a 503 Service Unavailable problem.
func ServiceUnavailable(title, detail string) Problem {
	return New(http.StatusServiceUnavailable, title).WithDetail(detail)
}
